accounts/urls.py
from django.conf.urls import url
from .views import *

app_name='accounts'

urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),

]

firstproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', home_view, name='home'),

    url(r'^post/', include('post.urls')),

    url(r'^accounts/', include('accounts.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from .views import *

app_name='posst'

urlpatterns = [
    url(r'^index/$', post_index,name='index'),
    url(r'^create/$', post_create,name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail,name='detail'),
    url(r'^(?P<slug>[\w-]+)/update/$', post_update,name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete,name='delete'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render


def home_view(request):
	if request.user.is_authenticated :
		context={
			'isim':request.user.first_name,
		}
	else:
		context={
			'isim':'Misafir'
		}
	return render(request,'home.html',context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="eng">
<head>
	<meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
	<title>Acm Hacettepe Blog - {% block title %}{% endblock %}</title>
    <link rel="stylesheet"
          href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

	{% include 'header.html' %}

	{% include 'messages.html' %}

	{% block body %}

	{% endblock %}
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</body>
</html>

templates/header.html
<!-- Navbar Start -->

<nav class="navbar navbar-inverse nevbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand">BLOGUM</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="{{ request.GET.q }}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated and request.user.is_staff %}
                    <li><a href="{% url 'posst:create' %}">YAZI EKLE</a></li>
                {% endif %}
                <li><a href="{% url 'home' %}">Anasayfa</a></li>
                <li><a href="{% url 'posst:index' %}">Blog</a></li>
                <li><a href="#">Hakkımda</a></li>
                <li><a href="#">İletişim</a></li>

                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:register' %}">UYE OL</a></li>
                    <li><a href="{% url 'accounts:login' %}">GIRIS</a></li>
                {% else %}
                <li><a href="{% url 'accounts:logout' %}">CIKIS</a></li>
                {% endif %}
            </ul>

        </nav>

    </div>
</nav>

templates/home.html
{% extends 'base.html' %}

{% block title %} ANASAYFA - {{ block.super }} {% endblock %}

{% block body %}

	<div class="container-fluid">
		<div class="row" style="margin-bottom:30px; ">
			<div class="col-md-4 col-sm-6 " style="background-color: red; height: 100px;">1.STUT</div>
			<div class="col-md-4 col-sm-6 " style="background-color: blue; height: 100px;" >2.STUT</div>
			<div class="col-md-4 col-sm-6 " style="background-color: green; height: 100px;">3.STUT</div>
			<div class="col-md-4 col-sm-6 " style="background-color: yellow; height: 100px;" >4.STUT</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-4" style="background-color: red; height: 100px;"></div>
		<div class="col-md-8" style="background-color: yellow; height: 100px;" >
			<div class="row">
				<div class="col-md-2" style="background-color: brown; height: 100px;"></div>
				<div class="col-md-8" style="background-color: green; height: 100px;"></div>
				<div class="col-md-1" style="background-color: blue; height: 100px;"></div>
			</div>
		</div>
		  WELCOME  {{ request.user.get_full_name }}
          e posta {{ request.user.email }}
	</div>

{% endblock %}

templates/messages.html
	{% if messages %}

		{% for msg in  messages %}

			<div class="alert alert-success alert-dismissible" role="alert">
			  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			  {{ msg }}
			</div>

		{% endfor %}

	{% endif %}